services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: countries_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
  
  countries_app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DB_NAME: countries_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432

volumes: 
  postgres_data:
